services:
  - type: web
    name: world-cup-2026-predictor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
